name: Lint and Test

on: [push, pull_request]

jobs:
  lint:
    name: Check lint and prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '22.x'
      - run: npm install
      - run: npm run lint
      - run: npm run prettier
        env:
          CI: true
  test:
    name: Test on node 22 and ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js 22
        uses: actions/setup-node@v6
        with:
          node-version: '22'
      - run: npm install
      - run: npm test
        env:
          CI: true
